name: Deploy Docs

on:
  push:
    branches: [main]
    paths:
      - 'docs/**'
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Upload docs artifact
        uses: actions/upload-artifact@v4
        with:
          name: docs-site
          path: docs

      # Static site deployment via Kai's artifact store.
      # The artifact is available for download and can be served
      # by a CDN or static hosting service pointed at the store.
      - name: Deploy notification
        run: |
          echo "Documentation artifact uploaded successfully."
          echo "Docs can be served from the artifact store."
          echo "Contents:"
          find docs -type f | head -20
